MOVIEAPP/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MOVIEAPP.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MOVIEAPP/Models/ErrorViewModel.cs
using System;

namespace MOVIEAPP.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MOVIEAPP/Models/Movie.cs
namespace MOVIEAPP.Models
{
    public class Movie
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string ShortDescription { get; set; }

        public string Description { get; set; }

        public string ImageUrl { get; set; }

        public int CategoryId { get; set; }

    }
}

MOVIEAPP/Models/ProductCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MOVIEAPP.Models
{
    public class ProductCategoryModel
    {
        public Movie Movie { get; set; }

        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

MOVIEAPP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MOVIEAPP.Data;
using MOVIEAPP.Models;

namespace MOVIEAPP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index(int? id)
        {
            //ProductCategoryModel productCategory = new ProductCategoryModel();
            //productCategory.Movies = MovieRepository.Movies;
            //productCategory.Categories = CategoryRepository.Categories;
            List<Movie> movies = MovieRepository.Movies;
            if(id != null)
            {
                movies = movies.Where(s => s.CategoryId == id).ToList();
            }

            return View(movies);
        }

        public IActionResult Details(int id)
        {
            //ProductCategoryModel model = new ProductCategoryModel();
            //model.Categories = CategoryRepository.Categories;
            //model.Movie = MovieRepository.GetById(id);
            return View(MovieRepository.GetById(id));
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MOVIEAPP/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MOVIEAPP.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }

        public IActionResult List()
        {
            return View();
        }
    }
}

MOVIEAPP/ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MOVIEAPP.Data;
using System;

namespace MOVIEAPP.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if(RouteData?.Values["action"].ToString() == "Details")
            {
                ViewBag.SelectedCategory = MovieRepository.GetById(Convert.ToInt32(RouteData?.Values["id"].ToString())).CategoryId.ToString();
            }
            else
            {
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            }


            return View(CategoryRepository.Categories);
        }
    }
}

MOVIEAPP/Views/Home/Details.cshtml
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Movie

<div class="row">
    <div class="col-md-3">
        @*@Html.Partial("_menu", Model.Categories)*@
        @await Component.InvokeAsync("CategoryMenu") 
    </div>
    <div class="col-md-9">
        <div class="card mb-3">

            <div class="card-body">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="~/img/@Model.ImageUrl" alt="" class="card-img" />
                    </div>
                    <div class="col-md-8">
                        <h5 class="card-title">
                            <a asp-action="Details" asp-controller="Home" asp-route-id="@Model.Id">
                                @Model.Name
                            </a>
                            @*<a href="/home/details/@item.Id">@item.Name</a>*@
                        </h5>
                        <p class="card-text">
                            @Html.Raw(Model.Description)
                        </p>
                        <p class="card-text">
                            <small class="text-muted">3 days ago</small>
                        </p>
                    </div>
                </div>
            </div>




        </div>
    </div>
</div>

MOVIEAPP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<Movie>

<div class="row">
    <div class="col-md-3">
        @*@Html.Partial("_menu", Model.Categories)*@
        @await Component.InvokeAsync("CategoryMenu") 
    </div>
    <div class="col-md-9">
        @*@Html.Partial("_movies", Model)*@
        <partial name="_movies" model="Model"></partial>
    </div>
</div>

MOVIEAPP/Views/Home/_movies.cshtml
@model IEnumerable<Movie>


@foreach (Movie item in Model)
{
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="~/img/@(item.ImageUrl)" alt="" class="card-img" />
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title">
                        <a asp-action="Details" asp-controller="Home" asp-route-id="@item.Id">
                            @item.Name
                        </a>
                        @*<a href="/home/details/@item.Id">@item.Name</a>*@                    
                    </h5>
                    <p class="card-text">
                        @item.ShortDescription
                    </p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>

                </div>
            </div>
        </div>
    </div>
}

MOVIEAPP/Views/Movie/Index.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_menu")
    </div>
    <div class="col-md-9">
        <partial name="_movies" model="Model" />
    </div>
</div>

MOVIEAPP/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

    <div class="list-group">
        <a asp-controller="Home" asp-action="Index" asp-route-id=""
           class="list-group-item list-group-item-action">
            Hepsi
        </a>
        @foreach (var item in Model)
        {
            <a asp-controller="Home" asp-action="Index" asp-route-id="@item.Id"
               class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==item.Id.ToString()? "active" : "")">
                @item.Name
            </a>
        }
    </div>

MOVIEAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MOVIEAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @Html.Partial("_navbar")
    </header>
    <main>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </main>

    <footer class="border-top footer text-muted">
        @Html.Partial("_footer")
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MOVIEAPP/Views/Shared/_footer.cshtml
<div class="container">
    &copy; 2020 - MOVIEAPP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>

MOVIEAPP/Views/Shared/_menu.cshtml
@model IEnumerable<Category>
    <div class="list-group">

        @foreach (var item in Model)
        {
            <a href="#" class="list-group-item list-group-item-action">@item.Name</a>
        }
    </div>

MOVIEAPP/Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">Movie App</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">login</a> 
            </li>
            <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>  
            </li>
        </ul>
    </div>
</div>